name: tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  run-node-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Run docker compose
        run: docker-compose up -d

      - name: Run node tests
        run: npm test

      - name: Run browser tests
        run: npm run test:browser

  run-deno-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        deno-version: [1.17.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Deno Version ${{ matrix.deno-version }}
        uses: denolib/setup-deno@v2
        with:
          deno-version: ${{ matrix.deno-version }}

      - name: Run deno tests
        run: deno run test/deno/test.ts
