name: tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Run docker compose
        run: docker-compose up -d

      - name: Run tests
        run: npm test

      - name: Run browser tests
        run: npm run test:browser
